name: 'CI - Backend'

env:
  IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')/backend
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/backend/*'
      - 'fix/backend/*'
  pull_request:
    branches:
      - 'feature/backend/*'
      - 'fix/backend/*'

jobs:
  build:
    name: 'Backend: Build'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: backend
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  code-quality:
    name: 'Backend: Code quality'
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: backend
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'Run code quality checks'
        run: |
          pip install "black" "isort"
      - name: 'Lint with Black'
        uses: psf/black@stable
        with:
          options: '--exclude=tests/'
          src: backend/src/
      - name: 'Lint with isort'
        run: |
          isort --check-only --profile black .

  tests:
    name: 'Backend: Tests'
    needs: build
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:14.2-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    ### add env variables
    env:
      BACKEND_SERVER_HOST: ${{ secrets.BACKEND_SERVER_HOST }}
      BACKEND_SERVER_PORT: ${{ secrets.BACKEND_SERVER_PORT }}
      BACKEND_SERVER_WORKERS: ${{ secrets.BACKEND_SERVER_WORKERS }}
      IS_ALLOWED_CREDENTIALS: ${{ secrets.IS_ALLOWED_CREDENTIALS }}
      STATIC_FILE_DIRECTORY: ${{ secrets.STATIC_FILE_DIRECTORY }}
      ALLOWED_ORIGIN_FRONTEND_LOCALHOST_DEFAULT: ${{ secrets.ALLOWED_ORIGIN_FRONTEND_LOCALHOST_DEFAULT }}
      ALLOWED_ORIGIN_FRONTEND_LOCALHOST_CUSTOM: ${{ secrets.ALLOWED_ORIGIN_FRONTEND_LOCALHOST_CUSTOM }}
      ALLOWED_ORIGIN_FRONTEND_DOCKER: ${{ secrets.ALLOWED_ORIGIN_FRONTEND_DOCKER }}
      ALLOWED_ORIGIN_FRONTEND_PRODUCTION: ${{ secrets.ALLOWED_ORIGIN_FRONTEND_PRODUCTION }}
      ALLOWED_METHOD_1: ${{ secrets.ALLOWED_METHOD_1 }}
      ALLOWED_HEADER_1: ${{ secrets.ALLOWED_HEADER_1 }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}
      POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
      POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      OAUTH2_TOKEN_URL: ${{ secrets.OAUTH2_TOKEN_URL }}
      POSTGRES_DEV_HOST: ${{ secrets.POSTGRES_DEV_HOST }}
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
      DB_TIMEOUT: ${{ secrets.DB_TIMEOUT }}
      DB_POOL_SIZE: ${{ secrets.DB_POOL_SIZE }}
      DB_MAX_POOL_CON: ${{ secrets.DB_MAX_POOL_CON }}
      DB_POOL_OVERFLOW: ${{ secrets.DB_POOL_OVERFLOW }}
      IS_DB_ASYNC_DRIVER: ${{ secrets.IS_DB_ASYNC_DRIVER }}
      IS_DB_EXPIRE_ON_COMMIT: ${{ secrets.IS_DB_EXPIRE_ON_COMMIT }}
      IS_DB_ECHO_LOG: ${{ secrets.IS_DB_ECHO_LOG }}
      IS_DB_FORCE_ROLLBACK: ${{ secrets.IS_DB_FORCE_ROLLBACK }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_SUBJECT: ${{ secrets.JWT_SUBJECT }}
      JWT_TOKEN_PREFIX: ${{ secrets.JWT_TOKEN_PREFIX }}
      JWT_ALGORITHM: ${{ secrets.JWT_ALGORITHM }}
      JWT_MIN: ${{ secrets.JWT_MIN }}
      JWT_HOUR: ${{ secrets.JWT_HOUR }}
      JWT_DAY: ${{ secrets.JWT_DAY }}
      BCRYPT_HASHING_ALGORITHM: ${{ secrets.BCRYPT_HASHING_ALGORITHM }}
      ARGON2_HASHING_ALGORITHM: ${{ secrets.ARGON2_HASHING_ALGORITHM }}
      SHA256_HASHING_ALGORITHM: ${{ secrets.SHA256_HASHING_ALGORITHM }}
      SHA512_HASHING_ALGORITHM: ${{ secrets.SHA512_HASHING_ALGORITHM }}
      HASHING_SALT: ${{ secrets.HASHING_SALT }}
      PWD_ALGORITHM_LAYER_1: ${{ secrets.PWD_ALGORITHM_LAYER_1 }}
      PWD_ALGORITHM_LAYER_2: ${{ secrets.PWD_ALGORITHM_LAYER_2 }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_POKEMON_IMAGE_DIR: ${{ secrets.AWS_S3_POKEMON_IMAGE_DIR }}
      AWS_S3_SKLEARN_MODEL_DIR: ${{ secrets.AWS_S3_SKLEARN_MODEL_DIR }}
      AWS_S3_TF_MODEL_DIR: ${{ secrets.AWS_S3_TF_MODEL_DIR }}
      AWS_S3_PT_MODEL_DIR: ${{ secrets.AWS_S3_PT_MODEL_DIR }}
      AWS_S3_BUCKET_ARN: ${{ secrets.AWS_S3_BUCKET_ARN }}
      AWS_S3_POKEMON_IMAGE_URI: ${{ secrets.AWS_S3_POKEMON_IMAGE_URI }}
      AWS_S3_SKLEARN_MODEL_URI: ${{ secrets.AWS_S3_SKLEARN_MODEL_URI }}
      AWS_S3_TF_MODEL_URI: ${{ secrets.AWS_S3_TF_MODEL_URI }}
      AWS_S3_PT_MODEL_URI: ${{ secrets.AWS_S3_PT_MODEL_URI }}
      AWS_IAM_USERNAME: ${{ secrets.AWS_IAM_USERNAME }}
      AWS_IAM_ARN: ${{ secrets.AWS_IAM_ARN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SERVICE_NAME: ${{ secrets.AWS_SERVICE_NAME }}
      AWS_SERVICE_REGION: ${{ secrets.AWS_SERVICE_REGION }}
      TF_MODEL_FILE_EXTENSION: ${{ secrets.TF_MODEL_FILE_EXTENSION }}
      SKLEARN_MODEL_FILE_EXTENSION: ${{ secrets.SKLEARN_MODEL_FILE_EXTENSION }}
      PYTORCH_MODEL_FILE_EXTENSION: ${{ secrets.PYTORCH_MODEL_FILE_EXTENSION }}
      STATIC_DIR_NAME: ${{ secrets.STATIC_DIR_NAME }}
      API_HEADER_KEY_TITLE: ${{ secrets.API_HEADER_KEY_TITLE }}
      API_COOKIE_KEY_TITLE: ${{ secrets.API_COOKIE_KEY_TITLE }}
      API_QUERY_KEY_TITLE: ${{ secrets.API_QUERY_KEY_TITLE }}
      SKLEARN_MODEL_FILE_EXTENSION_1: ${{ secrets.SKLEARN_MODEL_FILE_EXTENSION_1}}
      TF_MODEL_FILE_EXTENSION_1: ${{ secrets.TF_MODEL_FILE_EXTENSION_1 }}
      TF_MODEL_FILE_EXTENSION_2: ${{ secrets.TF_MODEL_FILE_EXTENSION_2 }}
      PT_MODEL_FILE_EXTENSION_1: ${{ secrets.PT_MODEL_FILE_EXTENSION_1 }}
      PT_MODEL_FILE_EXTENSION_2: ${{ secrets.PT_MODEL_FILE_EXTENSION_2 }}
      POSTGRES_TEST_HOST: ${{ secrets.POSTGRES_TEST_HOST }}
      CLIENT_CERT_PATH: ${{ secrets.CLIENT_CERT_PATH }}
      CLIENT_KEY_PATH: ${{ secrets.CLIENT_KEY_PATH }}
      SERCER_CA_PATH: ${{ secrets.SERVER_CA_PATH }}
      
    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 'Install dependencies for tests'
        run: |
          pip install pytest pytest-asyncio pytest-xdist pytest-cov
      - name: 'Run tests'
        run: |
          pytest --cov --cov-report=xml .

  docker-build:
    name: 'Backend: Docker build'
    needs: [tests, code-quality]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Login to GitHub Container Registry'
        run: echo {CICD_GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_GITHUB_TOKEN }}
      - name: 'Pull Image'
        run: docker pull ${{ env.IMAGE }}:latest || true
      - name: 'Build Image'
        run: docker build \
          --cache-from ${{ env.IMAGE }}:latest\
          --tag ${{ env.IMAGE }}:latest . \
          --file ./backend/Dockerfile.production \
          "./backend"
      - name: 'Push Image'
        run: docker push ${{ env.IMAGE }}:latest
